import type { SectionDef } from './workspace-sections'

function card(id: string, title: string, placeholder: string, aiTrigger: string) {
  return { id, title, placeholder, aiTrigger }
}

export const COMMUNICATION_SECTIONS: SectionDef[] = [
  {
    slug: 'sermao_inventio',
    title: 'Sermão · Invenção',
    shortTitle: 'Descoberta da mensagem',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'inventio',
    group: 'sermao_inventio',
    groupLabel: 'Invenção · Inventio',
    order: 100,
    objective: 'Transformar a exegese em uma mensagem proclamável, definindo a verdade central, a necessidade pastoral e o foco cristocêntrico do sermão.',
    keyQuestions: [
      'Qual verdade central deste texto precisa ser proclamada publicamente?',
      'Que problema do texto encontra o problema real do ouvinte?',
      'Como Cristo é fundamento, centro e motivação da mensagem?',
      'Qual resposta pastoral o sermão busca produzir?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Bryan Chapell', 'Sidney Greidanus', 'Timothy Keller'],
    cards: [
      card('sermao_ideia_central', 'Ideia Central', 'Formule a verdade central do sermão em uma sentença bíblica, clara e pregável.', 'Formule a ideia central de um sermão expositivo, argumentativo e pastoral para esta passagem.'),
      card('sermao_tema', 'Tema', 'Nomeie o tema dominante do sermão em linguagem simples e pastoral.', 'Identifique o tema homilético dominante desta passagem para uma pregação pública.'),
      card('sermao_proposicao', 'Proposição', 'Escreva a proposição que anuncia ao ouvinte o caminho do sermão.', 'Crie uma proposição proclamatória que introduza o argumento do sermão com força e clareza.'),
      card('sermao_objetivo', 'Objetivo do Sermão', 'Defina o que o sermão deve produzir em crença, afeto e obediência.', 'Defina o objetivo pastoral do sermão: o que os ouvintes devem crer, sentir e praticar.'),
      card('sermao_problema_texto', 'Problema do Texto', 'Identifique a tensão, pecado, dor ou conflito que o texto aborda originalmente.', 'Identifique o problema teológico e pastoral que a passagem confronta em seu contexto.'),
      card('sermao_problema_ouvinte', 'Problema do Ouvinte', 'Traduza a tensão do texto para a realidade da congregação contemporânea.', 'Mostre como o problema do texto aparece na vida de uma congregação reformada hoje.'),
      card('sermao_foco_cristocentrico', 'Foco Cristocêntrico', 'Explique como a pessoa e obra de Cristo sustentam a mensagem e evitam moralismo.', 'Mostre como Cristo é centro, fundamento e motivação deste sermão sem forçar conexões artificiais.'),
      card('sermao_argumento_principal', 'Argumento principal', 'Descreva a linha argumentativa que conduzirá o sermão do texto à resposta pastoral.', 'Construa o argumento principal do sermão, com progressão bíblica, homilética e persuasiva.'),
    ],
  },
  {
    slug: 'sermao_dispositio',
    title: 'Sermão · Disposição',
    shortTitle: 'Organização homilética',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'dispositio',
    group: 'sermao_dispositio',
    groupLabel: 'Disposição · Dispositio',
    order: 101,
    objective: 'Organizar a mensagem em fluxo homilético coerente, com progressão, equilíbrio, clímax, aplicações e conclusão.',
    keyQuestions: [
      'A estrutura nasce do texto e desenvolve a ideia central?',
      'Há progressão lógica e pastoral entre as partes?',
      'A introdução cria necessidade real e a conclusão chama à resposta?',
      'As aplicações são específicas, evangélicas e proporcionais ao texto?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Bryan Chapell', 'John Stott', 'Martyn Lloyd-Jones'],
    cards: [
      card('sermao_estrutura', 'Estrutura do Sermão', 'Descreva a arquitetura geral do sermão: introdução, pontos, aplicações e conclusão.', 'Proponha uma estrutura homilética coerente, textual e pastoral para este sermão.'),
      card('sermao_divisoes', 'Divisões', 'Liste as divisões principais com referência textual e função no argumento.', 'Crie divisões homiléticas derivadas do texto, paralelas quando possível e progressivas.'),
      card('sermao_progressao_logica', 'Progressão lógica', 'Explique como cada parte avança a tese do sermão.', 'Avalie e fortaleça a progressão lógica do sermão, evitando pontos soltos.'),
      card('sermao_introducao', 'Introdução', 'Construa uma abertura que capture atenção, revele necessidade e conduza ao texto.', 'Redija uma introdução pastoral que leve naturalmente à leitura e exposição da passagem.'),
      card('sermao_transicoes', 'Transições', 'Redija transições entre introdução, pontos, aplicações e conclusão.', 'Crie transições fluidas que resumam o ponto anterior e abram o próximo movimento.'),
      card('sermao_climax', 'Clímax', 'Identifique o ponto de maior peso teológico e pastoral do sermão.', 'Indique onde o sermão deve atingir seu clímax e como preparar esse momento.'),
      card('sermao_conclusao', 'Conclusão', 'Reforce a ideia central e conduza o ouvinte a uma resposta bíblica.', 'Redija uma conclusão que sintetize o argumento e chame à resposta em Cristo.'),
      card('sermao_aplicacoes', 'Aplicações', 'Desenvolva aplicações de fé, arrependimento, consolo e obediência.', 'Sugira aplicações específicas, cristocêntricas e pastoralmente sensíveis para esta congregação.'),
    ],
  },
  {
    slug: 'sermao_elocutio',
    title: 'Sermão · Elocução',
    shortTitle: 'Forma de comunicação',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'elocutio',
    group: 'sermao_elocutio',
    groupLabel: 'Elocução · Elocutio',
    order: 102,
    objective: 'Lapidar a linguagem do sermão para que a verdade bíblica seja comunicada com clareza, força, beleza e ternura pastoral.',
    keyQuestions: [
      'A linguagem é clara sem perder densidade bíblica?',
      'As ilustrações servem ao texto ou competem com ele?',
      'O tom combina com a intenção pastoral da passagem?',
      'Há frases memoráveis que fixam a verdade central?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Bryan Chapell', 'Charles Spurgeon', 'Timothy Keller'],
    cards: [
      card('sermao_clareza', 'Clareza', 'Reescreva frases centrais para que sejam diretas, orais e compreensíveis.', 'Revise a clareza do sermão com foco em frases curtas, voz ativa e precisão teológica.'),
      card('sermao_linguagem_pastoral', 'Linguagem pastoral', 'Ajuste a linguagem para falar com autoridade bíblica e cuidado de pastor.', 'Torne a linguagem mais pastoral, firme e terna, sem perder a autoridade do texto.'),
      card('sermao_ilustracoes', 'Ilustrações', 'Escolha histórias ou exemplos que iluminem a verdade sem dominar o sermão.', 'Sugira ilustrações fiéis ao texto e adequadas a uma congregação reformada.'),
      card('sermao_analogias', 'Analogias', 'Crie analogias que tornem conceitos abstratos visíveis e memoráveis.', 'Proponha analogias simples e precisas para comunicar a verdade central.'),
      card('sermao_retorica', 'Retórica', 'Use repetição, contraste, pergunta e clímax para fortalecer a persuasão bíblica.', 'Aprimore a força retórica do sermão com recursos discretos e textualmente adequados.'),
      card('sermao_enfases', 'Ênfases', 'Marque frases, ideias e momentos que devem receber peso especial.', 'Indique as ênfases verbais e argumentativas que reforçam o movimento do sermão.'),
      card('sermao_tom', 'Tom', 'Defina o tom predominante: consolador, profético, celebrativo, exortativo ou contemplativo.', 'Calibre o tom do sermão segundo o texto e a necessidade da congregação.'),
      card('sermao_imagens_verbais', 'Imagens verbais', 'Desenvolva imagens concretas que ajudem a congregação a ver a verdade.', 'Crie imagens verbais bíblicas e cotidianas para tornar o sermão vívido.'),
      card('sermao_frases_impacto', 'Frases de impacto', 'Escreva frases memoráveis que sintetizem a mensagem sem soar artificiais.', 'Sugira frases de impacto que sejam bíblicas, memoráveis e pastoralmente responsáveis.'),
    ],
  },
  {
    slug: 'sermao_memoria',
    title: 'Sermão · Memória',
    shortTitle: 'Internalização',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'memoria',
    group: 'sermao_memoria',
    groupLabel: 'Memória · Memoria',
    order: 103,
    objective: 'Internalizar o sermão para pregá-lo com domínio, naturalidade e dependência espiritual, sem depender mecanicamente do manuscrito.',
    keyQuestions: [
      'Qual é a estrutura mental mais simples do sermão?',
      'Que frases-chave precisam ser lembradas exatamente?',
      'Onde o pregador tem maior chance de perder o fluxo?',
      'Como a prática em voz alta ajustará o sermão?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Martyn Lloyd-Jones', 'Charles Spurgeon'],
    cards: [
      card('sermao_revisao', 'Revisão', 'Planeje a revisão final do conteúdo, das transições e das aplicações.', 'Crie um plano de revisão do sermão antes da pregação.'),
      card('sermao_fixacao', 'Fixação', 'Defina como fixar a lógica principal sem decorar cada frase.', 'Sugira métodos de fixação da estrutura homilética e dos movimentos principais.'),
      card('sermao_estrutura_mental', 'Estrutura mental', 'Reduza o sermão a um mapa mental simples e pregável.', 'Converta o sermão em uma estrutura mental clara para o púlpito.'),
      card('sermao_memorabilidade', 'Memorabilidade', 'Aprimore o que ajudará pregador e ouvintes a lembrar a mensagem.', 'Identifique elementos de memorabilidade sem sacrificar fidelidade bíblica.'),
      card('sermao_frases_chave', 'Frases-chave', 'Liste frases essenciais que devem ser pregadas com precisão.', 'Selecione frases-chave para memorizar e repetir durante o sermão.'),
      card('sermao_fluxo_mental', 'Fluxo mental', 'Descreva o sermão como uma narrativa de pensamento, de início a fim.', 'Explique o fluxo mental do sermão em linguagem coloquial para facilitar a pregação.'),
    ],
  },
  {
    slug: 'sermao_pronuntiatio',
    title: 'Sermão · Entrega',
    shortTitle: 'Execução da pregação',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'pronuntiatio',
    group: 'sermao_pronuntiatio',
    groupLabel: 'Entrega · Pronuntiatio',
    order: 104,
    objective: 'Planejar a execução pública do sermão, usando voz, ritmo, pausas, gestos e presença pastoral a serviço do texto.',
    keyQuestions: [
      'Como a voz deve acompanhar o movimento do texto?',
      'Onde pausas e ritmo ajudarão a congregação a processar a verdade?',
      'Que gestos ou movimentos podem reforçar, sem distrair?',
      'A intensidade comunica urgência pastoral ou mera performance?',
    ],
    relevantAuthors: ['Haddon Robinson', 'John Stott', 'Martyn Lloyd-Jones'],
    cards: [
      card('sermao_entonacao', 'Entonação', 'Planeje variações de tom conforme o movimento pastoral do sermão.', 'Sugira entonações adequadas aos momentos de consolo, confronto, celebração e apelo.'),
      card('sermao_ritmo', 'Ritmo', 'Indique onde acelerar, desacelerar ou deixar a frase respirar.', 'Planeje o ritmo da pregação para sustentar atenção e compreensão.'),
      card('sermao_pausas', 'Pausas', 'Marque pausas intencionais após afirmações de peso.', 'Indique pausas estratégicas que deem peso à mensagem sem teatralidade.'),
      card('sermao_gestos', 'Gestos', 'Defina gestos naturais que reforcem enumeração, contraste ou convite.', 'Sugira gestos simples e intencionais para apoiar a comunicação pastoral.'),
      card('sermao_comunicacao_pastoral', 'Comunicação pastoral', 'Planeje como falar como pastor presente, não como palestrante distante.', 'Ajuste a entrega para comunicar cuidado pastoral, autoridade bíblica e proximidade.'),
      card('sermao_intensidade', 'Intensidade', 'Calibre a energia emocional sem manipulação.', 'Indique onde a intensidade deve subir ou baixar de acordo com o texto.'),
      card('sermao_enfase_vocal', 'Ênfase vocal', 'Escolha palavras e frases que devem receber ênfase vocal.', 'Marque ênfases vocais para tornar a linha argumentativa mais clara.'),
    ],
  },
  {
    slug: 'sermao_avaliacao',
    title: 'Sermão · Avaliação',
    shortTitle: 'Pós-sermão',
    phase: 'comunicar',
    communicationMode: 'sermao',
    module: 'pronuntiatio',
    group: 'sermao_avaliacao',
    groupLabel: 'Avaliação',
    order: 105,
    objective: 'Avaliar a pregação entregue para crescer em fidelidade bíblica, clareza, aplicação e cuidado pastoral.',
    keyQuestions: [
      'O sermão foi fiel ao texto e claro para a congregação?',
      'As aplicações foram específicas e evangélicas?',
      'O tempo serviu à mensagem?',
      'Que feedback revela oportunidades reais de crescimento?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Bryan Chapell', 'Timothy Keller'],
    cards: [
      card('sermao_fidelidade_biblica', 'Fidelidade bíblica', 'Avalie se a mensagem proclamada correspondeu à intenção do texto.', 'Crie critérios para avaliar a fidelidade bíblica deste sermão após a pregação.'),
      card('sermao_avaliacao_clareza', 'Clareza', 'Registre onde a congregação pareceu compreender ou se perder.', 'Avalie a clareza do sermão e sugira melhorias concretas.'),
      card('sermao_avaliacao_aplicacao', 'Aplicação', 'Avalie se os ouvintes saíram sabendo como responder ao texto.', 'Avalie a força, especificidade e centralidade evangélica das aplicações.'),
      card('sermao_tempo', 'Tempo', 'Compare o tempo planejado com o tempo real e seus efeitos.', 'Ajude a avaliar se o tempo do sermão serviu ou prejudicou a comunicação.'),
      card('sermao_feedback', 'Feedback', 'Registre feedback de ouvintes e mentores, distinguindo impressão de diagnóstico.', 'Sugira perguntas para receber feedback útil sobre este sermão.'),
      card('sermao_melhorias_futuras', 'Melhorias futuras', 'Defina uma habilidade homilética concreta para desenvolver.', 'Indique melhorias futuras e exercícios práticos para crescimento homilético.'),
    ],
  },
  {
    slug: 'estudo_inventio',
    title: 'Estudo Bíblico · Invenção',
    shortTitle: 'Objetivo didático',
    phase: 'comunicar',
    communicationMode: 'estudo_biblico',
    module: 'inventio',
    group: 'estudo_inventio',
    groupLabel: 'Invenção · Inventio',
    order: 120,
    objective: 'Definir o objetivo didático do estudo bíblico, conectando a exegese ao aprendizado progressivo e participativo do grupo.',
    keyQuestions: [
      'O que o grupo precisa compreender ao final do encontro?',
      'Que conhecimentos prévios precisam ser ativados?',
      'Qual problema central organizará a conversa?',
      'Que contexto é necessário sem transformar o estudo em aula técnica?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott', 'Gordon Fee', 'Douglas Stuart'],
    cards: [
      card('estudo_objetivo', 'Objetivo do Estudo', 'Defina o aprendizado principal esperado para o grupo.', 'Defina um objetivo didático claro e mensurável para um estudo bíblico desta passagem.'),
      card('estudo_tema', 'Tema', 'Nomeie o tema do estudo em linguagem acessível para discussão.', 'Identifique o tema do estudo bíblico com linguagem didática e convidativa.'),
      card('estudo_problema_central', 'Problema central', 'Formule a questão central que guiará a investigação do grupo.', 'Formule uma pergunta-problema que organize o estudo bíblico de modo participativo.'),
      card('estudo_contexto_necessario', 'Contexto necessário', 'Liste apenas o contexto indispensável para entender o texto.', 'Selecione o contexto bíblico e histórico necessário para explicar a passagem ao grupo.'),
      card('estudo_conhecimentos_previos', 'Conhecimentos prévios', 'Identifique o que o grupo provavelmente já sabe, pressupõe ou confunde.', 'Mapeie conhecimentos prévios e possíveis confusões do grupo sobre esta passagem.'),
    ],
  },
  {
    slug: 'estudo_dispositio',
    title: 'Estudo Bíblico · Disposição',
    shortTitle: 'Estrutura pedagógica',
    phase: 'comunicar',
    communicationMode: 'estudo_biblico',
    module: 'dispositio',
    group: 'estudo_dispositio',
    groupLabel: 'Disposição · Dispositio',
    order: 121,
    objective: 'Organizar o estudo como uma progressão pedagógica com explicação, perguntas, participação e fixação.',
    keyQuestions: [
      'A sequência ajuda o grupo a descobrir antes de receber respostas prontas?',
      'As perguntas conduzem ao texto ou apenas à opinião?',
      'Há espaço real para participação e síntese?',
      'Os exercícios reforçam o aprendizado central?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott', 'D. A. Carson'],
    cards: [
      card('estudo_estrutura_pedagogica', 'Estrutura pedagógica', 'Desenhe o encontro em blocos de abertura, observação, interpretação, aplicação e síntese.', 'Monte uma estrutura pedagógica para conduzir o grupo por esta passagem.'),
      card('estudo_sequencia_topicos', 'Sequência de tópicos', 'Ordene os tópicos do simples ao complexo.', 'Organize os tópicos do estudo em sequência didática progressiva.'),
      card('estudo_organizacao_didatica', 'Organização didática', 'Defina tempo, ritmo e função de cada parte.', 'Sugira uma organização didática com tempos aproximados e objetivos por bloco.'),
      card('estudo_perguntas', 'Perguntas', 'Crie perguntas de observação, interpretação, doutrina e aplicação.', 'Crie perguntas bíblicas, abertas e progressivas para discussão em grupo.'),
      card('estudo_progressao_ensino', 'Progressão do ensino', 'Explique como o grupo avançará do texto à compreensão e à prática.', 'Avalie a progressão pedagógica do estudo e fortaleça sua lógica.'),
      card('estudo_exercicios', 'Exercícios', 'Planeje atividades simples de leitura, marcação, comparação ou síntese.', 'Sugira exercícios participativos que ajudem o grupo a trabalhar o texto.'),
      card('estudo_participacao', 'Participação', 'Defina como envolver diferentes perfis do grupo sem perder direção.', 'Proponha estratégias para participação equilibrada e bíblica durante o estudo.'),
    ],
  },
  {
    slug: 'estudo_elocutio',
    title: 'Estudo Bíblico · Elocução',
    shortTitle: 'Clareza didática',
    phase: 'comunicar',
    communicationMode: 'estudo_biblico',
    module: 'elocutio',
    group: 'estudo_elocutio',
    groupLabel: 'Elocução · Elocutio',
    order: 122,
    objective: 'Comunicar a passagem com clareza didática, exemplos acessíveis e explicações progressivas que favoreçam compreensão coletiva.',
    keyQuestions: [
      'A explicação é simples sem ser superficial?',
      'Que exemplos ajudarão o grupo a compreender?',
      'Quais termos precisam ser traduzidos para linguagem acessível?',
      'A linguagem convida à aprendizagem ou intimida?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott', 'Gordon Fee'],
    cards: [
      card('estudo_clareza_didatica', 'Clareza didática', 'Reescreva explicações para que o grupo consiga acompanhar passo a passo.', 'Torne as explicações desta passagem didáticas, simples e progressivas.'),
      card('estudo_exemplos', 'Exemplos', 'Escolha exemplos que ajudem a compreender conceitos bíblicos.', 'Sugira exemplos concretos para explicar os principais conceitos do texto.'),
      card('estudo_analogias', 'Analogias', 'Use analogias breves que iluminem sem simplificar demais.', 'Proponha analogias didáticas que ajudem o grupo a entender a passagem.'),
      card('estudo_simplificacao', 'Simplificação', 'Reduza explicações técnicas ao essencial sem perder precisão.', 'Simplifique pontos técnicos da exegese para um estudo bíblico em grupo.'),
      card('estudo_linguagem_acessivel', 'Linguagem acessível', 'Substitua jargões por explicações compreensíveis.', 'Adapte a linguagem para participantes com diferentes níveis de formação bíblica.'),
      card('estudo_explicacoes_progressivas', 'Explicações progressivas', 'Divida explicações complexas em degraus pedagógicos.', 'Estruture explicações progressivas que conduzam do conhecido ao novo.'),
    ],
  },
  {
    slug: 'estudo_memoria',
    title: 'Estudo Bíblico · Memória',
    shortTitle: 'Fixação',
    phase: 'comunicar',
    communicationMode: 'estudo_biblico',
    module: 'memoria',
    group: 'estudo_memoria',
    groupLabel: 'Memória · Memoria',
    order: 123,
    objective: 'Planejar revisão, síntese e repetição pedagógica para que o grupo retenha a verdade central do texto.',
    keyQuestions: [
      'Quais pontos o grupo precisa lembrar ao sair?',
      'Como a síntese será construída coletivamente?',
      'Que repetição ajudará sem soar mecânica?',
      'Como retomar o estudo na próxima reunião?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott'],
    cards: [
      card('estudo_revisao', 'Revisão', 'Planeje como retomar os aprendizados durante e ao final do encontro.', 'Crie um plano de revisão para fixar a aprendizagem do estudo bíblico.'),
      card('estudo_sintese', 'Síntese', 'Escreva uma síntese que o grupo possa repetir e guardar.', 'Formule uma síntese didática da passagem para o grupo memorizar.'),
      card('estudo_pontos_chave', 'Pontos-chave', 'Liste os pontos indispensáveis que não podem se perder.', 'Identifique os pontos-chave que o grupo precisa reter.'),
      card('estudo_fixacao', 'Fixação', 'Defina recursos de fixação: quadro, pergunta final, resumo, tarefa.', 'Sugira recursos de fixação adequados a um estudo bíblico participativo.'),
      card('estudo_repeticao_pedagogica', 'Repetição pedagógica', 'Planeje repetições intencionais da ideia central.', 'Indique como repetir a verdade central de forma natural e pedagógica.'),
    ],
  },
  {
    slug: 'estudo_pronuntiatio',
    title: 'Estudo Bíblico · Entrega',
    shortTitle: 'Condução do grupo',
    phase: 'comunicar',
    communicationMode: 'estudo_biblico',
    module: 'pronuntiatio',
    group: 'estudo_pronuntiatio',
    groupLabel: 'Entrega · Pronuntiatio',
    order: 124,
    objective: 'Conduzir o estudo com interação, ritmo, perguntas e dinâmica que favoreçam participação e aprendizado bíblico.',
    keyQuestions: [
      'Como estimular participação sem perder direção?',
      'Que perguntas devem ser feitas em voz alta e em que ordem?',
      'Qual ritmo permite pensar, responder e aprender?',
      'Que dinâmica serve ao texto e não distrai dele?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott'],
    cards: [
      card('estudo_interacao', 'Interação', 'Planeje como ouvir, responder e redirecionar contribuições.', 'Sugira estratégias de interação para conduzir um estudo bíblico participativo.'),
      card('estudo_participacao_entrega', 'Participação', 'Defina momentos de fala do grupo, leitura e reflexão.', 'Planeje momentos de participação ativa durante o estudo.'),
      card('estudo_dinamica', 'Dinâmica', 'Escolha uma dinâmica simples que sirva ao objetivo do texto.', 'Proponha uma dinâmica discreta e bíblica para apoiar o aprendizado do grupo.'),
      card('estudo_ritmo_ensino', 'Ritmo de ensino', 'Calibre explicação, silêncio, perguntas e respostas.', 'Ajuste o ritmo de ensino para manter atenção e compreensão.'),
      card('estudo_perguntas_grupo', 'Perguntas ao grupo', 'Liste perguntas-chave na ordem em que serão feitas.', 'Organize perguntas ao grupo em progressão observação, interpretação e aplicação.'),
    ],
  },
  {
    slug: 'devocional_inventio',
    title: 'Devocional · Invenção',
    shortTitle: 'Verdade e consolo',
    phase: 'comunicar',
    communicationMode: 'devocional',
    module: 'inventio',
    group: 'devocional_inventio',
    groupLabel: 'Invenção · Inventio',
    order: 140,
    objective: 'Discernir a verdade espiritual central do texto para conduzir o leitor a esperança, consolo, exortação e comunhão com Deus.',
    keyQuestions: [
      'Que verdade do texto deve ser contemplada?',
      'Que esperança ou consolo emerge da passagem?',
      'Que exortação precisa ser recebida com mansidão?',
      'Qual chamado espiritual o texto faz hoje?',
    ],
    relevantAuthors: ['Charles Spurgeon', 'John Stott', 'Sinclair Ferguson', 'Timothy Keller'],
    cards: [
      card('devocional_verdade_central', 'Verdade central', 'Formule a verdade espiritual que sustentará o devocional.', 'Identifique a verdade central da passagem para um devocional pastoral e contemplativo.'),
      card('devocional_esperanca', 'Esperança', 'Mostre que esperança o texto oferece em Deus e em Cristo.', 'Explique a esperança que esta passagem oferece ao coração do leitor.'),
      card('devocional_consolo', 'Consolo', 'Nomeie o consolo pastoral do texto para pessoas cansadas, aflitas ou tentadas.', 'Extraia o consolo pastoral da passagem com sensibilidade e fidelidade bíblica.'),
      card('devocional_exortacao', 'Exortação', 'Defina a correção ou convite à obediência que o texto apresenta.', 'Formule uma exortação devocional que seja bíblica, terna e não moralista.'),
      card('devocional_chamado_espiritual', 'Chamado espiritual', 'Escreva o chamado final à fé, oração, arrependimento ou descanso.', 'Defina o chamado espiritual que este devocional deve fazer ao leitor.'),
    ],
  },
  {
    slug: 'devocional_dispositio',
    title: 'Devocional · Disposição',
    shortTitle: 'Fluxo meditativo',
    phase: 'comunicar',
    communicationMode: 'devocional',
    module: 'dispositio',
    group: 'devocional_dispositio',
    groupLabel: 'Disposição · Dispositio',
    order: 141,
    objective: 'Organizar o devocional como uma jornada breve, contemplativa e pastoral, conduzindo da leitura à meditação e à resposta pessoal.',
    keyQuestions: [
      'O fluxo conduz o leitor a contemplar antes de agir?',
      'A progressão espiritual é natural e simples?',
      'A aplicação é pessoal sem ser individualista?',
      'Há uma jornada emocional coerente com o texto?',
    ],
    relevantAuthors: ['Eugene Peterson', 'Sinclair Ferguson', 'Charles Spurgeon'],
    cards: [
      card('devocional_fluxo_meditativo', 'Fluxo meditativo', 'Desenhe o percurso: texto, contemplação, aplicação, oração.', 'Organize um fluxo meditativo simples para este devocional.'),
      card('devocional_progressao_espiritual', 'Progressão espiritual', 'Mostre como o leitor será conduzido de atenção para resposta.', 'Crie uma progressão espiritual coerente com a passagem.'),
      card('devocional_aplicacao_pessoal', 'Aplicação pessoal', 'Escreva uma aplicação íntima, concreta e evangélica.', 'Sugira uma aplicação pessoal centrada no evangelho para este devocional.'),
      card('devocional_jornada_emocional', 'Jornada emocional', 'Identifique o movimento afetivo: inquietação, consolo, confiança, adoração.', 'Mapeie a jornada emocional adequada ao texto sem sentimentalismo.'),
    ],
  },
  {
    slug: 'devocional_elocutio',
    title: 'Devocional · Elocução',
    shortTitle: 'Linguagem contemplativa',
    phase: 'comunicar',
    communicationMode: 'devocional',
    module: 'elocutio',
    group: 'devocional_elocutio',
    groupLabel: 'Elocução · Elocutio',
    order: 142,
    objective: 'Dar ao devocional uma linguagem simples, bela, sensível e pastoral, sem parecer aula nem sermão técnico.',
    keyQuestions: [
      'A linguagem cria espaço para meditação?',
      'Há beleza textual sem excesso ornamental?',
      'O tom é íntimo, reverente e bíblico?',
      'A simplicidade preserva profundidade?',
    ],
    relevantAuthors: ['Charles Spurgeon', 'Sinclair Ferguson', 'Eugene Peterson'],
    cards: [
      card('devocional_linguagem_pastoral', 'Linguagem pastoral', 'Fale ao coração com cuidado, verdade e reverência.', 'Reescreva a linguagem do devocional com tom pastoral e contemplativo.'),
      card('devocional_sensibilidade', 'Sensibilidade', 'Evite dureza desnecessária e sentimentalismo raso.', 'Ajuste a sensibilidade pastoral do devocional para leitores em diferentes condições espirituais.'),
      card('devocional_simplicidade', 'Simplicidade', 'Use frases simples que carreguem verdade profunda.', 'Simplifique a linguagem mantendo profundidade bíblica.'),
      card('devocional_beleza_textual', 'Beleza textual', 'Aprimore cadência, imagens e escolhas verbais com sobriedade.', 'Torne o texto mais belo e meditativo sem perder clareza.'),
      card('devocional_tom', 'Tom devocional', 'Defina o tom: consolo, arrependimento, gratidão, confiança ou adoração.', 'Calibre o tom devocional de acordo com a passagem.'),
    ],
  },
  {
    slug: 'devocional_memoria',
    title: 'Devocional · Memória',
    shortTitle: 'Internalização espiritual',
    phase: 'comunicar',
    communicationMode: 'devocional',
    module: 'memoria',
    group: 'devocional_memoria',
    groupLabel: 'Memória · Memoria',
    order: 143,
    objective: 'Ajudar o leitor a levar a verdade do texto consigo por meio de reflexão, oração, meditação e uma frase de retenção.',
    keyQuestions: [
      'Que frase pode acompanhar o leitor durante o dia?',
      'Como a oração nasce do texto?',
      'Que reflexão favorece internalização espiritual?',
      'O devocional convida à meditação real, não só à informação?',
    ],
    relevantAuthors: ['Sinclair Ferguson', 'Charles Spurgeon'],
    cards: [
      card('devocional_internalizacao', 'Internalização', 'Resuma como a verdade deve ser levada para a vida diária.', 'Crie um caminho de internalização espiritual para esta verdade bíblica.'),
      card('devocional_reflexao', 'Reflexão', 'Escreva uma pergunta de reflexão pessoal e reverente.', 'Formule perguntas de reflexão devocional baseadas no texto.'),
      card('devocional_oracao', 'Oração', 'Redija uma oração curta que responda à passagem.', 'Escreva uma oração pastoral, bíblica e sensível em resposta ao texto.'),
      card('devocional_meditacao', 'Meditação', 'Defina uma frase ou imagem para meditar ao longo do dia.', 'Sugira uma frase de meditação que fixe a verdade central no coração.'),
    ],
  },
  {
    slug: 'devocional_pronuntiatio',
    title: 'Devocional · Entrega',
    shortTitle: 'Leitura contemplativa',
    phase: 'comunicar',
    communicationMode: 'devocional',
    module: 'pronuntiatio',
    group: 'devocional_pronuntiatio',
    groupLabel: 'Entrega · Pronuntiatio',
    order: 144,
    objective: 'Preparar a leitura ou condução do devocional com pausas, ritmo contemplativo e espaço para meditação guiada.',
    keyQuestions: [
      'Como a leitura deve respirar?',
      'Onde o silêncio ajuda mais do que explicação?',
      'O ritmo conduz à oração e à confiança?',
      'A meditação guiada permanece subordinada ao texto?',
    ],
    relevantAuthors: ['Eugene Peterson', 'Sinclair Ferguson'],
    cards: [
      card('devocional_leitura', 'Leitura', 'Planeje a leitura do texto e do devocional em tom reverente.', 'Sugira uma forma de leitura devocional reverente para esta passagem.'),
      card('devocional_pausas', 'Pausas', 'Marque pausas para contemplação e oração silenciosa.', 'Indique pausas contemplativas que ajudem o leitor ou grupo a meditar.'),
      card('devocional_meditacao_guiada', 'Meditação guiada', 'Escreva uma condução breve para meditar na verdade do texto.', 'Crie uma meditação guiada breve, pastoral e centrada na passagem.'),
      card('devocional_ritmo_contemplativo', 'Ritmo contemplativo', 'Calibre o ritmo para que o conteúdo seja recebido, não apenas consumido.', 'Ajuste o ritmo contemplativo do devocional para favorecer oração e descanso em Deus.'),
    ],
  },
]
